name: trigger deploy

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    name: trigger
    if: |
      github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ github.event.comment.body }} 
      - name: Validate
        run: |
          if echo ${{ github.event.comment.body }} | grep -q -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'; then
            :
          else
            exit 0
          fi
      - name: Bar
        run: cat $GITHUB_EVENT_PATH
      - name: Foo
        run: echo ${{ github.event.comment.body }}
