name: trigger deploy

on:
  issue_comment:
    types:
      - created

jobs:
  validate:
    name: validate
    if: |
      github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Validate comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          if echo ${{ github.event.comment.body }} | grep -q -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'; then
            echo "OK. Deploy command is valid."
          else
            echo "NG. Deploy command is invalid. Cancelling the workflow ${GITHUB_RUN_ID}..."
            gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/cancel -X POST
          fi
  trigger-deploy:
    name: trigger-deploy
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - name: Echo deploy destination
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          DEPLOY_DESTINATION=$(echo ${{ github.event.comment.body }} | sed -e 's/^\/deploy[ \f\n\r\t]\+\([a-zA-Z0-9_\/-]\+\)$/\1/g')
          echo $DEPLOY_DESTINATION
          echo $CIRCLECI_TOKEN

