name: trigger deploy

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    name: trigger
    if: |
      github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: |
          echo ${{ github.event.comment.body }}
      - name: Test2
        run: |
          echo ${{ github.event.comment.body }} | grep -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'
      - name: Test3
        run: |
          echo "https://api.github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/cancel"
          gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} -X DELETE
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Validate
        run: |
          if echo ${{ github.event.comment.body }} | grep -q -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'; then
            echo 'succeed'
          else
            exit 'fail'
          fi
      - name: Bar
        run: cat $GITHUB_EVENT_PATH
      - name: Foo
        run: echo ${{ github.event.comment.body }}
