name: trigger deploy

on:
  issue_comment:
    types:
      - created

jobs:
  validate:
    name: validate
    if: |
      github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Validate comment
        run: |
          if echo ${{ github.event.comment.body }} | grep -q -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'; then
            :
          else
            gh api repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/cancel -X POST
            # sleep 1m
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  bar:
    name: bar
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - name: Bar
        run: echo "bar"
