name: trigger deploy

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    name: trigger
    if: |
      github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: echo ${{ github.event.comment.body }}
