name: Deploy for

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      deploy-destination:
        description: "the destination to deploy must be 'staging' or 'security'"
        required: true

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      deploy-destination: ${{ steps.validate-deploy-destination.outputs.test || steps.validate-comment.outputs.test }}
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy'))
    steps:
      - name: Validate the value of deploy-destination
        id: validate-deploy-destination
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          T=${{ github.event.inputs.deploy-destination }}
          if [ $T = 'staging' ] || [ $T = 'security' ]; then
              echo ::set-output name=test::$T
              echo "OK. The value of deploy-destination is $T."
          else
            echo "NG. The value of deploy-destination is invalid. Cancelling the workflow ${{ github.run_id }}..."
            gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel -X POST
          fi
      - name: Validate the comment
        id: validate-comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/deploy') }}
        # この setp の grep で用いている正規表現と sed の正規表現は同様のものです。
        # sed と grep で正規表現のルールが若干異なるため共通化ができませんでした。
        # 期待しているのは "/deploy staging" や "/deploy    security" という文字列です
        # "/deploystaging" や "/deploy staging security" というパターンは通らないようにチェックしています
        run: |
          function print_comment() {
            echo ${{ github.event.comment.body }}
          }
          function extract_deploy_destination() {
            print_comment | sed -e 's/^\/deploy[ \f\n\r\t]\+\([a-zA-Z0-9_\/-]\+\)$/\1/g'
          }

          VALID=0
          if print_comment | grep -q -E '^\/deploy\s+((\w|\d|\_|\-|\/)+)$'; then
            DEPLOY_DESTINATION=$(extract_deploy_destination)
            if [ $DEPLOY_DESTINATION = 'staging' ] || [ $DEPLOY_DESTINATION = 'security' ]; then
              VALID=1
              echo ::set-output name=test::$DEPLOY_DESTINATION
            fi
          fi
          if [ $VALID -eq 1 ]; then
            echo "OK. Deploy command is valid. The deploy destination is $DEPLOY_DESTINATION"
          else
            echo "NG. Deploy command is invalid. Cancelling the workflow ${{ github.run_id }}..."
            gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel -X POST
          fi
  trigger-deploy:
    name: trigger-deploy
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo ${{ needs.prepare.outputs.deploy-destination }}
      - name: Get the branch name
        id: get-branch-name
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          case ${{ github.event_name }} in
            'issue_comment' )
              echo ::set-output name=branch-name::$(gh api repos/${{ github.repository }}/pulls/${{ github.event.issue.number }} \
                | jq -r '.head.ref')
              ;;
            'workflow_dispatch' )
              echo '::set-output name=branch-name::${GITHUB_REF#refs/heads/}'
              ;;
            * )
              echo 'The event type must be issue_comment or workflow_dispatch'
              exit 1
              ;;
          esac
      - name: Triggers CircleCI pipeline
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          HTTP_STATUS=$(curl \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Circle-Token: $CIRCLECI_TOKEN" \
            -d "{\"branch\": \"${{ steps.get-branch-name.outputs.branch-name }}\", \"parameters\": { \"run-deploy\": true, \"deploy-destination\": \"${{ needs.prepare.outputs.deploy-destination }}\" } }" \
            https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline \
            -o output \
            -w '%{http_code}\n' \
            -s)
          if [ "$HTTP_STATUS" -lt 200 -o "$HTTP_STATUS" -ge 300 ]; then
            echo "API request for the CircleCI workflow fails with status code $HTTP_STATUS"
            echo 'the response body is'
            cat ./output
            exit 1
          fi
