name: manual

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "the branch name to deploy"
        required: true
      deploy-destination:
        description: "the destination to deploy"
        required: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Hoge
        run: |
          echo ${{ github.ref }}
          exit 1
  deploy:
    name: trigger-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Triggers CircleCI pipeline
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
        run: |
          curl \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Circle-Token: $CIRCLECI_TOKEN" \
            -d "{\"branch\": \"${{ github.event.inputs.branch-name }}\", \"parameters\": { \"run-deploy\": true, \"deploy-destination\": \"${{ github.event.inputs.deploy-destination }}\" } }" \
            https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline

