name: test

on:
  issue_comment:
    types:
      - created

jobs:
  test1:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.0.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Required mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Required mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: sugahara_naoto@kakaku.com
          # Required sender full name (address can be skipped):
          from: ${{ secrets.MAIL_USERNAME }} # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully! TEST_MESSAGE is ${{ secrets.TEST_MESSAGE }}

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.0.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Required mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Required mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: sugahara_naoto@kakaku.com
          # Required sender full name (address can be skipped):
          from: ${{ secrets.MAIL_USERNAME }} # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully! TEST_MESSAGE is ${{ secrets.TEST_MESSAGE }}
