name: test

on:
  issue_comment:
    types:
      - created

jobs:
  test1:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: echo
        run: |
          echo ${{ secrets.TEST_MESSAGE }} | grep .
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ secrets.TEST_MESSAGE }} | grep .
